environment:
  SSL_CERT_FILE: "C:\\OpenSSL\\cacert.pem"
  matrix:
    # 1.1.0, 64/32 bit
    - TARGET: i686-pc-windows-gnu
      BITS: 32
      MSYS2: 1
    - TARGET: x86_64-pc-windows-msvc
      BITS: 64
      OPENSSL_DIR: C:\OpenSSL
install:
  # install OpenSSL
  - ps: Start-FileDownload "http://slproweb.com/download/Win${env:BITS}OpenSSL-1_1_0d.exe"
  - Win%BITS%OpenSSL-1_1_0d.exe /SILENT /VERYSILENT /SP- /DIR="C:\OpenSSL"
  - ps: Start-FileDownload "https://curl.haxx.se/ca/cacert.pem" -FileName "C:\OpenSSL\cacert.pem"
  # Install Rust
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - if defined MSYS2 set PATH=C:\msys64\mingw%BITS%\bin;%PATH%
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo test -v

cache:
  - target
  - C:\Users\appveyor\.cargo\registry

notifications:
- provider: Slack
  auth_token:
    secure: kumJKSxARfmD/wO+rlhGEqOvMg8mYRx9gNDY/mE5xxlHOzGKcmMOtA3DrNPVmLAkZCQ+TnB7lWUJYUY/F6PWekFsBwIVHGKikbDPSDfU+hY=
  channel: '#ci'
