[package]

name = "hueclient"
version = "0.3.2"
authors = ["Mathieu Poumeyrol <kali@zoy.org>", "Bjarke Sørensen <bs@wasd.dk>"]
description = "Rust library for Philips Hue lights"
homepage = "http://github.com/gugi9000/hue.rs"
repository = "http://github.com/gugi9000/hue.rs"
readme = "README.md"
license = "MIT"
keywords = [ "Philips", "hue", "light", "bulb" ]

[dependencies]
regex = "0.1.17"
hyper = "0.9.10"
rustc-serialize = "0.3.0"
