[package]

name = "philipshue"
version = "0.0.1"
authors = [
  "Bjarke Sørensen <bs@wasd.dk>",
  "Lucas Falch Sørensen <lucas@wasd.dk>"
]
description = "Rust library for Philips Hue lights"
homepage = "http://orangenose.com/products/philipshue"
repository = "http://github.com/gugi9000/hue.rs"
readme = "README.md"
license = "MIT"
keywords = [ "Philips", "hue", "light", "bulb" ]

[dependencies]
regex = "0.1.17"
hyper = "0.9.10"
rustc-serialize = "0.3.0"
