[package]

name = "philipshue"
version = "0.0.2"
authors = [
  "Mathieu Poumeyrol <kali@zoy.org>",
  "Bjarke Sørensen <bs@wasd.dk>",
  "Lucas Falch Sørensen <lucas@wasd.dk>"
]
description = "Rust library for Philips Hue lights"
homepage = "http://www.orangenose.com/products/philipshue/"
repository = "http://github.com/Orangenosecom/philipshue"
readme = "README.md"
license = "MIT"
keywords = [ "Philips", "hue", "light", "bulb" ]
exclude = [
    ".gitignore",
    ".travis.yml",
    "appveyor.yml"
]
build = "build.rs"

[features]
default = ["serde_codegen"]
upnp = ["ssdp"]
unstable = ["serde_derive", "upnp"]

[build-dependencies]
serde_codegen = { version = "0.8", optional = true }

[dependencies]
regex = "0.1.17"
serde = "0.8"
serde_derive = { version = "0.8", optional = true }
serde_json = "0.8"
lazy_static = "0.2.1"
ssdp = { version = "0.3", optional = true }

[dependencies.hyper]
version = "0.9.11"
default-features = false
features = ["ssl", "serde-serialization"]
